nbrb:
  api:
    ratesUrl: https://api.nbrb.by/exrates/rates
spring:
  application:
    name: ExchangeRates
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  h2:
    console:
      enabled: true
  data:
    jdbc:
      dialect: h2